'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'welcome_back': 'Welcome Back',
    'create_account': 'Create Account',
    'farmer': 'Farmer',
    'buyer': 'Buyer',
    'email_address': 'Email Address',
    'password': 'Password',
    'log_in': 'Log In',
    'sign_up': 'Sign Up',
    'forgot_password': 'Forgot Password?',
    'or_continue_with': 'Or continue with',
    'trusted_by': 'Trusted by 12,000+ farmers',
    'market_trends': 'Market Trends',
    'smart_insights': 'Smart Farm Insights',
    'activity_center': 'Activity Center',
    'view_details': 'View Details',
    'mark_all_read': 'Mark all read',
    'loading_alerts': 'Loading Alerts...',
    'search': 'Search...',
    'my_profile': 'My Profile',
    'logout': 'Logout',
    'farm_overview': 'Farm Overview',
    'welcome_back_message': 'Here\'s what\'s happening today.',
    'shopping_cart': 'My Basket (Panier)',
    'theme_light': 'Theme switched to light mode',
    'theme_dark': 'Theme switched to dark mode',
    'logistics': 'MoMo Transport (Delivery)',
    'marketplace': 'The Marché',
    'marketplace_title': 'The Marché',
    'my_listings': 'My Boutique',
    'diagnose': 'Crop Doctor',
    'diagnostics': 'Diagnostics',
    'dashboard': 'Control Center',
    'main_menu': 'Direct Access',
    'close_menu': 'Close Menu',
    'pro_plan': 'Pro Plan',
    'upgrade_msg': 'Upgrade for advanced AI insights and global shipping.',
    'upgrade_now': 'Upgrade Now',
    'all': 'All',
    'active': 'Active',
    'completed': 'Completed',
    'destination': 'Destination',
    'courier': 'Courier',
    'est_arrival': 'Est. Arrival',
    'details': 'Details',
    'live_tracking': 'Live Tracking',
    'delivery_stats': 'Delivery Stats',
    'on_time_rate': 'On-Time Rate',
    'transit_time': 'Transit Time',
    'efficiency': 'Efficiency',
    'monthly_summary': 'Monthly Summary',
    'explore_map': 'Explore Fleet Map',
    'items': 'items',
    'field_status_map': 'Field Status Map',
    'satellite': 'Satellite',
    'heatmap': 'Heatmap',
    'live_monitoring': 'Live Monitoring Active',
    'orders_to_process': 'Orders to Process',
    'accept_order': 'Accept Order',
    'mark_shipped': 'Mark as Shipped',
    'past_diagnoses': 'Past Crop Diagnoses',
    'new_scan': 'New Scan',
    'total_revenue': 'Total Revenue',
    'crop_health': 'Crop Health',
    'total_inventory': 'Total Inventory',
    'pending_orders': 'Pending Orders',
    'active_orders': 'Active Orders',
    'total_spent': 'Total Spent',
    'purchase_history': 'Purchase History',
    'marketplace_overview': 'Marketplace Overview',
    'featured_products': 'Featured Products',
    'recent_orders': 'Recent Orders',
    'view_all': 'View All',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'pending': 'Pending',
    'details_btn': 'Details',
    'browse': 'Browse',
    'quick_actions': 'Quick Actions',
    'reorder': 'Reorder',
    'support': 'Support',
    'settings': 'Settings',
    'recent_activity': 'Recent Activity',
    'my_inventory': 'My Inventory',
    'weather_forecast': 'Weather Forecast',
    'humidity': 'Humidity',
    'wind': 'Wind',
    'precip': 'Precipitation',
    'hourly_temp': 'Hourly Temp',
    'manage_all': 'Manage All',
    'active_categories': 'Active Product Categories',
    'diagnosis_title': 'Plant Disease Diagnosis',
    'diagnosis_subtitle': 'AI-powered crop health analysis',
    'select_crop': 'Select Crop Type',
    'upload_image': 'Upload Leaf Image',
    'take_photo': 'Take Photo',
    'start_analysis': 'Start AI Analysis',
    'analyzing': 'DNA Analysis in progress...',
    'tomato': 'Tomato',
    'potato': 'Potato',
    'corn': 'Corn',
    'wheat': 'Wheat',
    'rice': 'Rice',
    'soybean': 'Soybean',
    'apple': 'Apple',
    'grape': 'Grape',
    'strawberry': 'Strawberry',
    'other': 'Other',
    'step_uploading': 'Uploading leaf image...',
    'step_analyzing': 'Analyzing symptoms...',
    'step_patterns': 'Identifying disease patterns...',
    'step_database': 'Consulting agricultural database...',
    'step_treatment': 'Generating treatment plan...',
    'step_finalizing': 'Finalizing report...',
    'marketplace_explorer': 'Explore The Marché',
    'marketplace_explorer_desc': 'Discover verified produce directly from local Cameroonian farms.',
    'sell_produce': 'Start Selling (Vendre)',
    'search_products_placeholder': 'Search products by name or description...',
    'tour': 'Tour',
    'compare': 'Compare',
    'filters': 'Filters',
    'sort': 'Sort',
    'sort_az': 'Name (A-Z)',
    'sort_price_low': 'Price: Low to High',
    'sort_price_high': 'Price: High to Low',
    'origin': 'Origin',
    'certifications': 'Certifications',
    'harvest_season': 'Harvest Season',
    'recently_viewed': 'Recently Viewed',
    'clear': 'Clear',
    'add_to_cart': 'ADD TO CART',
    'product_comparison': 'Product Comparison',
    'feature': 'Feature',
    'price': 'Price (XAF)',
    'location': 'Region/Market',
    'health_status': 'Health Status',
    'hero_title': 'Empowering the Next Generation of Cameroonian Farmers 🇨🇲.',
    'hero_desc': 'Connect directly with buyers, track transport via MoMo, and use AI to secure your harvest across all 10 regions.',
    'no_account': 'Don\'t have an account?',
    'have_account': 'Already have an account?',
    'full_name': 'Full Name',
    'market': 'Market',
    'climate': 'Climate',
    'all_caught_up': 'All caught up!',
    'no_alerts': 'No alerts found',
    'scroll_more': 'Scroll to see more',
    'view_background': 'View background notifications',
  },
  fr: {
    'welcome_back': 'Bon retour',
    'create_account': 'Créer un compte',
    'farmer': 'Agriculteur',
    'buyer': 'Acheteur',
    'email_address': 'Adresse Email',
    'password': 'Mot de passe',
    'log_in': 'Se connecter',
    'sign_up': 'S\'inscrire',
    'forgot_password': 'Mot de passe oublié?',
    'or_continue_with': 'Ou continuer avec',
    'trusted_by': 'Approuvé par plus de 12 000 agriculteurs',
    'market_trends': 'Tendances du Marché',
    'smart_insights': 'Conseils Agricoles',
    'activity_center': 'Centre d\'Activités',
    'view_details': 'Voir Détails',
    'mark_all_read': 'Tout marquer comme lu',
    'loading_alerts': 'Chargement des alertes...',
    'search': 'Rechercher...',
    'my_profile': 'Mon Profil',
    'logout': 'Se déconnecter',
    'farm_overview': 'Aperçu de la Ferme',
    'welcome_back_message': 'Voici ce qui se passe aujourd\'hui.',
    'shopping_cart': 'Mon Panier',
    'theme_light': 'Thème passé en mode clair',
    'theme_dark': 'Thème passé en mode sombre',
    'logistics': 'MoMo Transport',
    'marketplace': 'Le Marché',
    'marketplace_title': 'Le Marché',
    'my_listings': 'Ma Boutique',
    'diagnose': 'Docteur des Plantes',
    'diagnostics': 'Diagnostics',
    'dashboard': 'Centre de Contrôle',
    'main_menu': 'Accès Direct',
    'close_menu': 'Fermer le Menu',
    'pro_plan': 'Plan Pro',
    'upgrade_msg': 'Passez au niveau supérieur pour des conseils IA avancés.',
    'upgrade_now': 'Améliorer Maintenant',
    'all': 'Tout',
    'active': 'En cours',
    'completed': 'Terminé',
    'destination': 'Destination',
    'courier': 'Livreur',
    'est_arrival': 'Arrivée Estimée',
    'details': 'Détails',
    'live_tracking': 'Suivi en Direct',
    'delivery_stats': 'Statistiques de Livraison',
    'on_time_rate': 'Taux de Ponctualité',
    'transit_time': 'Temps de Transit',
    'efficiency': 'Efficacité',
    'monthly_summary': 'Résumé Mensuel',
    'explore_map': 'Explorer la Carte',
    'items': 'articles',
    'field_status_map': 'Carte du Domaine',
    'satellite': 'Satellite',
    'heatmap': 'Chaleur',
    'live_monitoring': 'Surveillance en Direct',
    'orders_to_process': 'Commandes à Traiter',
    'accept_order': 'Accepter',
    'mark_shipped': 'Marquer Expédié',
    'past_diagnoses': 'Historique Diagnostics',
    'new_scan': 'Nouveau Scan',
    'total_revenue': 'Revenu Total',
    'crop_health': 'Santé des Cultures',
    'total_inventory': 'Stock Total',
    'pending_orders': 'Commandes en attente',
    'active_orders': 'Commandes actives',
    'total_spent': 'Total dépensé',
    'purchase_history': 'Historique achats',
    'marketplace_overview': 'Aperçu du Marché',
    'featured_products': 'Produits en Vedette',
    'recent_orders': 'Commandes Récentes',
    'view_all': 'Tout Voir',
    'processing': 'Traitement',
    'shipped': 'Expédié',
    'delivered': 'Livré',
    'pending': 'En attente',
    'details_btn': 'Détails',
    'browse': 'Explorer',
    'quick_actions': 'Actions Rapides',
    'reorder': 'Commander encore',
    'support': 'Assistance',
    'settings': 'Paramètres',
    'recent_activity': 'Activité Récente',
    'my_inventory': 'Mon Inventaire',
    'weather_forecast': 'Prévisions Météo',
    'humidity': 'Humidité',
    'wind': 'Vent',
    'precip': 'Précipitations',
    'hourly_temp': 'Temp. Horaire',
    'manage_all': 'Gérer Tout',
    'active_categories': 'Catégories Actives',
    'diagnosis_title': 'Diagnostic des Maladies',
    'diagnosis_subtitle': 'Analyse de la santé des cultures par IA',
    'select_crop': 'Choisir le type de culture',
    'upload_image': 'Télécharger l\'image de la feuille',
    'take_photo': 'Prendre une photo',
    'start_analysis': 'Démarrer l\'analyse IA',
    'analyzing': 'Analyse ADN en cours...',
    'tomato': 'Tomate',
    'potato': 'Pomme de terre',
    'corn': 'Maïs',
    'wheat': 'Blé',
    'rice': 'Riz',
    'soybean': 'Soja',
    'apple': 'Pomme',
    'grape': 'Raisin',
    'strawberry': 'Fraise',
    'other': 'Autre',
    'step_uploading': 'Téléchargement de l\'image...',
    'step_analyzing': 'Analyse des symptômes...',
    'step_patterns': 'Identification des motifs...',
    'step_database': 'Consultation de la base de données...',
    'step_treatment': 'Génération du plan de traitement...',
    'step_finalizing': 'Finalisation du rapport...',
    'marketplace_explorer': 'Explorateur du Marché',
    'marketplace_explorer_desc': 'Découvrez des produits vérifiés provenant directement des fermes.',
    'sell_produce': 'Vendre vos Produits',
    'search_products_placeholder': 'Rechercher par nom ou description...',
    'tour': 'Visite',
    'compare': 'Comparer',
    'filters': 'Filtres',
    'sort': 'Trier',
    'sort_az': 'Nom (A-Z)',
    'sort_price_low': 'Prix: Croissant',
    'sort_price_high': 'Prix: Décroissant',
    'origin': 'Origine',
    'certifications': 'Certifications',
    'harvest_season': 'Saison de Récolte',
    'recently_viewed': 'Consultés Récemment',
    'clear': 'Effacer',
    'add_to_cart': 'AJOUTER AU PANIER',
    'product_comparison': 'Comparaison de Produits',
    'feature': 'Caractéristique',
    'price': 'Prix (FCFA)',
    'location': 'Région / Marché',
    'health_status': 'État de Santé',
    'hero_title': 'Autonomiser la nouvelle génération d\'agriculteurs camerounais 🇨🇲.',
    'hero_desc': 'Connectez-vous directement aux acheteurs, suivez le transport via MoMo et utilisez l\'IA pour sécuriser vos récoltes dans les 10 régions.',
    'no_account': 'Pas encore de compte?',
    'have_account': 'Déjà un compte?',
    'full_name': 'Nom complet',
    'market': 'Marché',
    'climate': 'Climat',
    'all_caught_up': 'Vous êtes à jour!',
    'no_alerts': 'Aucune alerte trouvée',
    'scroll_more': 'Faites défiler pour en voir plus',
    'view_background': 'Voir les notifications en arrière-plan',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'fr')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
