import { NavItem, Product } from './types';

export const SIDEBAR_NAV: NavItem[] = [
  { label: 'Dashboard', icon: 'dashboard', path: '/' },
  { label: 'Crop Doctor', icon: 'biotech', path: '/diagnosis', roles: ['farmer'] },
  { label: 'Logistics', icon: 'local_shipping', path: '/logistics', roles: ['farmer'] },
  { label: 'Payments', icon: 'history', path: '/history' },
  { label: 'Messages', icon: 'forum', path: '/messages' },
  { label: 'Profile', icon: 'account_circle', path: '/profile' },
];

export const MARKETPLACE_NAV: NavItem[] = [
  { label: 'Marketplace', icon: 'storefront', path: '/marketplace' },
  { label: 'Basket', icon: 'shopping_cart', path: '/cart' },
  { label: 'Messages', icon: 'forum', path: '/messages' },
  { label: 'My Boutique', icon: 'potted_plant', path: '/listings', roles: ['farmer'] },
  { label: 'Orders', icon: 'receipt_long', path: '/orders' },
  { label: 'Insights', icon: 'insights', path: '/insights', roles: ['farmer'] },
  { label: 'Logistics', icon: 'local_shipping', path: '/logistics', roles: ['farmer'] },
];

export const ADMIN_NAV: NavItem[] = [
  { label: 'Control Room', icon: 'terminal', path: '/admin/dashboard' },
  { label: 'Product Catalog', icon: 'inventory_2', path: '/admin/catalog' },
  { label: 'Dispute Center', icon: 'gavel', path: '/admin/disputes' },
  { label: 'Treasury Hub', icon: 'payments', path: '/admin/treasury' },
  { label: 'Safe Pay Hub', icon: 'shield_with_heart', path: '/admin/escrow' },
  { label: 'User Directory', icon: 'group', path: '/admin/users' },
  { label: 'System Audit', icon: 'history', path: '/admin/logs' },
  { label: 'Market Ledger', icon: 'account_balance_wallet', path: '/admin/transactions' },
  { label: 'System Settings', icon: 'settings_suggest', path: '/admin/settings' },
  { label: 'Exit Admin', icon: 'logout', path: '/' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'seed-product-1',
    farmer_id: 'sample-farmer',
    name: 'Fresh Plantains (Kumba)',
    description: 'High-grade yellow and green plantain bunches harvested from the nutrient-rich volcanic soils of Kumba. Perfect for frying dodo or making boiled plantains.',
    category: 'Foodstuff',
    price: 3500,
    unit: 'bunch',
    image_url: 'https://images.unsplash.com/photo-1566393028639-d108a42c46a7?w=800&q=80',
    stock_quantity: 50,
    initial_stock_quantity: 100,
    is_verified: true,
    location: 'Kumba',
    is_perishable: true,
    health_status: 'Perfect',
    certifications: ['Organic'],
    created_at: '2024-03-20T10:00:00Z',
    expiry_date: '2024-04-10T10:00:00Z',
  },
  {
    id: 'seed-product-2',
    farmer_id: 'sample-farmer',
    name: 'Yellow Garri (Mbouda)',
    description: 'Traditionally grated, fermented, and dry-fried cassava granules enriched with pure organic palm oil. Crisp, sour-sweet taste, excellent for drinking or preparing eba.',
    category: 'Foodstuff',
    price: 12500,
    unit: 'bag',
    image_url: 'https://images.unsplash.com/photo-1590602847076-2e86161405e1?w=800&q=80',
    stock_quantity: 40,
    initial_stock_quantity: 80,
    is_verified: true,
    location: 'Mbouda',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: ['Fair Trade'],
    created_at: '2024-03-19T09:00:00Z',
  },
  {
    id: 'seed-product-3',
    farmer_id: 'sample-farmer',
    name: 'Penja White Pepper',
    description: 'World-renowned geographic indication Penja White Pepper. Handpicked, washed in spring water, dry-sunned, offering an exceptionally intense and aromatic flavor profile.',
    category: 'Spices & Pepper',
    price: 10000,
    unit: 'kg',
    image_url: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&q=80',
    stock_quantity: 15,
    initial_stock_quantity: 30,
    is_verified: true,
    location: 'Penja',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: ['G-GAP', 'Organic'],
    created_at: '2024-03-15T14:30:00Z',
  },
  {
    id: 'seed-product-4',
    farmer_id: 'sample-farmer',
    name: 'Cameroon Njansang Seeds',
    description: 'Dried aromatic njansang seeds wild-harvested. An iconic Cameroonian cuisine spice crushed to thicken and season legendary fish, chicken, and traditional soup recipes.',
    category: 'Spices & Pepper',
    price: 5000,
    unit: 'bucket',
    image_url: 'https://images.unsplash.com/photo-1509210963774-7db9115a0407?w=800&q=80',
    stock_quantity: 25,
    initial_stock_quantity: 50,
    is_verified: true,
    location: 'Littoral',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: [],
    created_at: '2024-03-18T10:00:00Z',
  },
  {
    id: 'seed-product-5',
    farmer_id: 'sample-farmer',
    name: 'Pure Red Palm Oil (Manyu)',
    description: 'Rich, unrefined, traditionally pressed red palm oil from Manyu Division. Contains zero chemical additives or artificial coloring. High viscosity, perfect for Eru and Fufu.',
    category: 'Oils',
    price: 8500,
    unit: 'jerrycan',
    image_url: 'https://images.unsplash.com/photo-1622484211148-71749c40bcfe?w=800&q=80',
    stock_quantity: 35,
    initial_stock_quantity: 70,
    is_verified: true,
    location: 'Manyu',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: ['Organic'],
    created_at: '2024-03-14T11:00:00Z',
  },
  {
    id: 'seed-product-6',
    farmer_id: 'sample-farmer',
    name: 'Koki Beans (Foumbot)',
    description: 'Premium de-hulled black-eyed peas specifically optimized for making the traditional savory Koki bean cake. Soft, fast-cooking, high nutrient retention.',
    category: 'Grains & Beans',
    price: 1200,
    unit: 'bucket',
    image_url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&q=80',
    stock_quantity: 60,
    initial_stock_quantity: 120,
    is_verified: true,
    location: 'Foumbot',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: [],
    created_at: '2024-03-12T08:00:00Z',
  },
  {
    id: 'seed-product-7',
    farmer_id: 'sample-farmer',
    name: 'Ndop Red Rice',
    description: 'Nutritious, high-fiber red rice grains grown in the plain paddy fields of Ndop. Unpolished and completely local, delivering excellent home-cooked flavor.',
    category: 'Grains & Beans',
    price: 15000,
    unit: 'bag',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80',
    stock_quantity: 20,
    initial_stock_quantity: 50,
    is_verified: true,
    location: 'North West',
    is_perishable: false,
    health_status: 'Perfect',
    certifications: ['Fair Trade'],
    created_at: '2024-03-21T15:00:00Z',
  },
  {
    id: 'seed-product-8',
    farmer_id: 'sample-farmer',
    name: 'Njombe Pineapples',
    description: 'Extra sweet, fragrant, and heavily juicy pineapples freshly harvested from Njombe farms. High vitamin content, hand-selected at optimal ripeness.',
    category: 'Fruits',
    price: 500,
    unit: 'piece',
    image_url: 'https://images.unsplash.com/photo-1550258114-68bd295056a2?w=800&q=80',
    stock_quantity: 120,
    initial_stock_quantity: 150,
    is_verified: true,
    location: 'Njombe',
    is_perishable: true,
    health_status: 'Perfect',
    certifications: ['Organic'],
    created_at: '2024-03-18T08:00:00Z',
    expiry_date: '2024-04-05T20:00:00Z',
  },
  {
    id: 'seed-product-9',
    farmer_id: 'sample-farmer',
    name: 'Mshada Avocados (Foumban)',
    description: 'Buttery, rich, large-size avocados locally known as Mshada from the hills of Foumban. Creamy flesh, small pit, packed with healthy fats.',
    category: 'Fruits',
    price: 1500,
    unit: 'heap',
    image_url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&q=80',
    stock_quantity: 30,
    initial_stock_quantity: 60,
    is_verified: true,
    location: 'Foumban',
    is_perishable: true,
    health_status: 'Perfect',
    certifications: [],
    created_at: '2024-03-22T07:30:00Z',
    expiry_date: '2024-04-03T18:00:00Z',
  },
  {
    id: 'seed-product-10',
    farmer_id: 'sample-farmer',
    name: 'Local Free-Range Chicken (West)',
    description: 'Traditional tough "village chicken" raised free-range in the fields of West Cameroon. High density, flavorful farm-reared meat prized for traditional Ndole or pepper soup.',
    category: 'Meat & Eggs',
    price: 6500,
    unit: 'piece',
    image_url: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&q=80',
    stock_quantity: 18,
    initial_stock_quantity: 40,
    is_verified: true,
    location: 'West',
    is_perishable: true,
    health_status: 'Perfect',
    certifications: ['Organic'],
    created_at: '2024-03-23T11:45:00Z',
    expiry_date: '2024-03-31T23:59:59Z',
  },
  {
    id: 'seed-product-11',
    farmer_id: 'sample-farmer',
    name: 'Foumbot Cabbage Crate',
    description: 'Huge, crisp, heavy heads of green cabbage grown in the humid valleys of Foumbot. Exceptionally crunchy, clean, and locally packed in standard wooden crates.',
    category: 'Vegetables',
    price: 3500,
    unit: 'crate',
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    stock_quantity: 22,
    initial_stock_quantity: 45,
    is_verified: true,
    location: 'Foumbot',
    is_perishable: true,
    health_status: 'Perfect',
    certifications: [],
    created_at: '2024-03-24T06:15:00Z',
    expiry_date: '2024-04-14T10:00:00Z',
  }
];
