import { NavItem, Product } from './types';

export const SIDEBAR_NAV: NavItem[] = [
  { label: 'Dashboard', icon: 'dashboard', path: '/' },
  { label: 'Diagnosis', icon: 'biotech', path: '/diagnosis', roles: ['farmer'] },
  { label: 'Logistics', icon: 'local_shipping', path: '/logistics', roles: ['farmer'] },
  { label: 'History', icon: 'history', path: '/history' },
  { label: 'Messages', icon: 'forum', path: '/messages' },
  { label: 'Profile', icon: 'account_circle', path: '/profile' },
];

export const MARKETPLACE_NAV: NavItem[] = [
  { label: 'Marketplace', icon: 'storefront', path: '/marketplace' },
  { label: 'Cart', icon: 'shopping_cart', path: '/cart' },
  { label: 'Messages', icon: 'forum', path: '/messages' },
  { label: 'My Listings', icon: 'potted_plant', path: '/listings', roles: ['farmer'] },
  { label: 'Insights', icon: 'insights', path: '/insights', roles: ['farmer'] },
  { label: 'Logistics', icon: 'local_shipping', path: '/logistics', roles: ['farmer'] },
  { label: 'My Orders', icon: 'shopping_bag', path: '/orders', roles: ['buyer'] },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    farmer_id: 'farmer-1',
    name: 'White Cassava (Manihot)',
    price: 500,
    unit: 'kg',
    location: 'Littoral, Cameroon',
    image_url: 'https://picsum.photos/seed/cassava/400/300',
    is_verified: true,
    health_status: 'Excellent',
    certifications: ['Organic'],
    harvest_season: 'Year-round',
    category: 'Tubers',
    description: 'High-quality white cassava from the Littoral region. Perfect for making garri or fufu.',
    stock_quantity: 2000,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-1',
      full_name: 'Jean-Pierre Eto\'o',
      email: 'jean@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer1/100/100',
      is_verified: true,
      location_name: 'Douala, Littoral'
    }
  },
  {
    id: '2',
    farmer_id: 'farmer-2',
    name: 'Premium Cocoa Beans',
    price: 1500,
    unit: 'kg',
    location: 'South West, Cameroon',
    image_url: 'https://picsum.photos/seed/cocoa/400/300',
    is_verified: true,
    health_status: 'Good',
    certifications: ['Fair Trade'],
    harvest_season: 'Main Crop',
    category: 'Cash Crops',
    description: 'Sun-dried premium cocoa beans from the fertile volcanic soils of the South West.',
    stock_quantity: 5000,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-2',
      full_name: 'Marie-Claire Ngono',
      email: 'marie@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer2/100/100',
      is_verified: true,
      location_name: 'Kumba, South West'
    }
  },
  {
    id: '3',
    farmer_id: 'farmer-3',
    name: 'Sweet Plantains',
    price: 3000,
    unit: 'bunch',
    location: 'West, Cameroon',
    image_url: 'https://picsum.photos/seed/plantain/400/300',
    is_verified: true,
    health_status: 'Excellent',
    certifications: [],
    harvest_season: 'Year-round',
    category: 'Fruits',
    description: 'Large, sweet plantains from the highlands of the West region.',
    stock_quantity: 150,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-3',
      full_name: 'Samuel Kamga',
      email: 'samuel@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer3/100/100',
      is_verified: true,
      location_name: 'Bafoussam, West'
    }
  },
  {
    id: '4',
    farmer_id: 'farmer-4',
    name: 'Arabica Coffee Beans',
    price: 2500,
    unit: 'kg',
    location: 'North West, Cameroon',
    image_url: 'https://picsum.photos/seed/coffee/400/300',
    is_verified: true,
    health_status: 'Excellent',
    certifications: ['Organic', 'Fair Trade'],
    harvest_season: 'Harvest',
    category: 'Cash Crops',
    description: 'Aromatic Arabica coffee beans grown at high altitudes in the North West.',
    stock_quantity: 1200,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-4',
      full_name: 'Florence Bih',
      email: 'florence@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer4/100/100',
      is_verified: true,
      location_name: 'Bamenda, North West'
    }
  },
  {
    id: '5',
    farmer_id: 'farmer-5',
    name: 'Yellow Maize',
    price: 250,
    unit: 'kg',
    location: 'Adamawa, Cameroon',
    image_url: 'https://picsum.photos/seed/maize/400/300',
    is_verified: true,
    health_status: 'Good',
    certifications: [],
    harvest_season: 'Summer',
    category: 'Grains',
    description: 'High-yield yellow maize, perfect for poultry feed or human consumption.',
    stock_quantity: 10000,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-5',
      full_name: 'Abdoulaye Bello',
      email: 'abdou@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer5/100/100',
      is_verified: true,
      location_name: 'Ngaoundéré, Adamawa'
    }
  },
  {
    id: '6',
    farmer_id: 'farmer-6',
    name: 'Fresh Ndole Leaves',
    price: 1000,
    unit: 'bundle',
    location: 'Littoral, Cameroon',
    image_url: 'https://picsum.photos/seed/ndole/400/300',
    is_verified: true,
    health_status: 'Excellent',
    certifications: [],
    harvest_season: 'Year-round',
    category: 'Vegetables',
    description: 'Freshly harvested Ndole leaves, a staple for the famous Cameroonian dish.',
    stock_quantity: 80,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'farmer-6',
      full_name: 'Therese Mpondo',
      email: 'therese@example.cm',
      role: 'farmer',
      avatar_url: 'https://picsum.photos/seed/farmer6/100/100',
      is_verified: true,
      location_name: 'Douala, Littoral'
    }
  },
];
